# Generated by Django 4.1.3 on 2022-11-22 12:06

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(max_length=600)),
                ("lesson", models.TextField(default="")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("visibility", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now=True)),
                ("unlock_password", models.IntegerField(default=0, max_length=8)),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=256)),
                ("definition", models.TextField(max_length=600)),
                ("favorite", models.BooleanField(default=False)),
                ("is_learned", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.cardgroup",
                    ),
                ),
            ],
        ),
    ]
