# Generated by Django 4.1.3 on 2022-12-03 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardGroup',
            new_name='CardDeck',
        ),
    ]
