# Generated by Django 4.1.3 on 2022-12-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_question_responce"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
